version: '3'

services:
  db:
    image: 'postgres'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nestjs
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
